### ISSUE TITLE
Battery SOC goes under 0% and switch to 105%

### ISSUE THREAD

**Issue by buddhafragt** [stuartpittaway/diyBMS-CurrentShunt#12]
I have the problem, when the battery reach 0% the SOC switch to 105%.
I think there is something wrong in the SOC calculation....

**Comment by stuartpittaway** [comment]
It sounds like the battery capacity isn't set properly.


Can you send a screenshot of the current monitor page?

**Comment by stuartpittaway** [comment]
The code to calculate the state of charge has been changed, can you try the latest version and report back?
