### ISSUE TITLE
measurement inaccuracy?

### ISSUE THREAD

**Issue by MatthiasN73** [stuartpittaway/diyBMS-CurrentShunt#13]
Hi Stuart, my current shunt has always a reading of about 4 µV (18 mA) while no charger or load is connected.
Is it possible to calibrate this out or do I have to accept it.

**Comment by stuartpittaway** [comment]
Unfortunately this is likely to be noise on the cables, so nothing that can easily be zero'ed out.  It may be possible to do this via a software change in the future.

Do you know if the 18mA is constant across the whole current measurement range?

**Comment by MatthiasN73** [comment]
No idea.
I only have a current clamp for such high currents and i think its not very accurate.
