### ISSUE TITLE
Current reading not correct

### ISSUE THREAD

**Issue by stefanK74** [stuartpittaway/diyBMS-CurrentShunt#16]
The shunt board (500A/50mV) seems to be electrically working, but current readings are not correct.
The displayed current/power values also do not correlate to the amps going in or out.
The shunt´s voltage reading seems to be ok.

Upon powering up the shunt the green/red leds flash: 5xgreen, 1x red, then periodicaly green and red
Shunt is installed in the positive cable.
Vsense wire is connected to the battery.

Platform & Version
Host name: DIYBMS-009C7938
Processor: ESP32
Version: 7eebc8252a0a6f83da919580a9e9534cacd37f4d
Compiled: 2023-02-14T09:29:32.618Z
Language: en
SDK Version: v4.4.3
Min free Heap: 87912
Free heap: 99280
Heap size: 283788

Any help would be highly appreciated!
Thanks!

At this point in time the batteries were charged with about 47 Amps.
mqtt: {"valid":1,"voltage":54.029,"current":-0.0639,"power":3.5919,"mAhIn":0,"mAhOut":10,"temperature":24,"relayState":0,"soc":89.49}

![current monitor](https://user-images.githubusercontent.com/37181195/219627215-9ef24ef6-30e5-4597-ab9f-a4f47b9588f7.png)

**Comment by stuartpittaway** [comment]
Ok, assume the shunt voltage @ 54.02V is correct.

Can you confirm that the shunt is installed in the POSITIVE cable - AFTER all the 4 banks merge together.

You then also have the two sensor wires connected to the shunt (normally screw terminals) directly to the shunt PCB (normally soldered to board).

Additionally, you have two power feeds going directly from the battery (after positive merged together) to both "+++" and "+VSENSE" terminals ?

A very crude diagram...

![image](https://user-images.githubusercontent.com/1201909/219634137-9fffefa7-33af-4c48-beb9-c26b61a304cc.png)

**Comment by stefanK74** [comment]
>Can you confirm that the shunt is installed in the POSITIVE cable - AFTER all the 4 banks merge together.
Yes.

>You then also have the two sensor wires connected to the shunt (normally screw terminals) directly to the shunt PCB (normally soldered to board).
Yes, 2 sensor wires soldered to the board.

>Additionally, you have **two power feeds** going directly from the battery (after positive merged together) to both "+++" and "+VSENSE" terminals ?
I have **1 power feed / positive cable** going from the battery to the shunt and bridge "+++" and "+VSense" on the screw terminals on the shunt board.

**Comment by stuartpittaway** [comment]
Thanks, given how low the current reading is, there may be a short/solder bridge on the input terminals.

Can you **disconnect** both of the wires to the shunt "kelvin" connections (small screw terminals) and using a multimeter, test the resistance between the two sensor wires?

Additionally, check the resistance between pins 9 and 10 on the INA228 chip, as those pins are only 0.5mm apart, I suspect there's a very small solder bridge between those two pins - or one of them is not soldered to the PCB correctly.


If you check between pin 9 and the right hand sensor wire (when viewed from rear), you should have 10ohm resistance.  Again between pin 10 and the other wire, should be 10ohm.

![image](https://user-images.githubusercontent.com/1201909/219642295-867b8a31-fcdf-4f41-8248-703fc48cbe56.png)

**Comment by stefanK74** [comment]
Looks like you pointed me in the right direction:
I checked the resistance of R1 only and the multimeter showed 300k - should be 10ohm.
For R2 (just the resistor) it didn´t show any value at all as well as between the two shunt wires.
I´ll populate a new board and measure resistances once done - thanks for now!

**Comment by stuartpittaway** [comment]
Ok - you might be able to just re-heat the existing board to sort out the solder joints.

**Comment by red0909** [comment]
i have the 500 amp 50mv shunt too
works for me

**Comment by stuartpittaway** [comment]
@stefanK74 did you get this fixed?

**Comment by stefanK74** [comment]
Unfortunately not, I resoldered the INA228 and checked pin9+10, but that didn´t help. I need to look into it one more time..

**Comment by stefanK74** [comment]
I assume it´s a soldering issue and put the board on the shelf..
Since INA228s are available again I will populate a new board.
Thanks everyone for your feedback!
