### ISSUE TITLE
README.md, CODE section updi link is wrong!

### ISSUE THREAD

**Issue by virtuvas** [stuartpittaway/diyBMS-CurrentShunt#20]
stuart,

the link in the Programming section of the code tap regarding the updi programming is not valid. 
Author has moved it to here:

https://www.hackster.io/john-bradnam/create-your-own-updi-programmer-1e55f1

best if you update the readme.md, took me some time to figure it out last week!

cheers

V.

**Comment by stuartpittaway** [comment]
Thanks, I've updated the README.
