### ISSUE TITLE
CPL files

### ISSUE THREAD

**Issue by BorisvdsHA** [stuartpittaway/diyBMS-CurrentShunt#21]
CPL files do not seem correct for BMS and shunt. JLPCB refuses to go further. Says positions are missing.

**Comment by BorisvdsHA** [comment]
ModuleV490-AllInOne and shunt

**Comment by stuartpittaway** [comment]
What is the exact message you are receiving?  Can you upload a screenshot?

**Comment by BorisvdsHA** [comment]
I downloaded the gerber zip file, Jl BOM and cpl from this folder. The RAW files.

[diyBMS-CurrentShunt](https://github.com/stuartpittaway/diyBMS-CurrentShunt/tree/master)/[CurrentShuntCircuit](https://github.com/stuartpittaway/diyBMS-CurrentShunt/tree/master/CurrentShuntCircuit)
/export/

**Comment by BorisvdsHA** [comment]
![Schermafbeelding 2023-10-18 om 19 33 34](https://github.com/stuartpittaway/diyBMS-CurrentShunt/assets/122743538/636b78d6-2ad2-4c9c-8544-95268b01e9b4)

**Comment by BorisvdsHA** [comment]
I added the gerber, works perfect. I added BOM and CPL, works perfect. But the next step does not work. Gives this error. I think it is also the case for the BMS 16s.

Nevertheless great work, looking if I can put it together. I have have used easyeda before to test. I have a little experience with esphome an HA. Thanks.

**Comment by stuartpittaway** [comment]
That's a new message JLC have introduced recently - you can ignore it, they cannot fit those parts so they are excluded from the BOM

**Comment by BorisvdsHA** [comment]
OK thanks.
